/* eslint-disable */
/* tslint:disable */
//----------------------
// <auto-generated>
// Generated using Swaggie (https://github.com/yhnavein/swaggie)
// Please avoid doing any manual changes in this file
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
// deno-lint-ignore-file

import Axios, { AxiosPromise, AxiosRequestConfig } from 'axios';

export const axios = Axios;
/**
 * @description 新增审批
 * @param {any}      [req]           [required]  req
 */

export type postSystemAuditAddProps = {
  req: AuditReq;
};

export const postSystemAuditAdd = (
  { req }: postSystemAuditAddProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/audit/add`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 新增字典分类
 * @param {any}      [req]           [required]  req
 */

export type postSystemDictdataAddProps = {
  req: DictDataReq;
};

export const postSystemDictdataAdd = (
  { req }: postSystemDictdataAddProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/dictdata/add`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 新增字典枚举值
 * @param {any}      [req]           [required]  req
 */

export type postSystemDictenumAddProps = {
  req: DictEnumReq;
};

export const postSystemDictenumAdd = (
  { req }: postSystemDictenumAddProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/dictenum/add`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 新增字典
 * @param {any}      [req]           [required]  req
 */

export type postSystemDicttypeAddProps = {
  req: DictTypeReq;
};

export const postSystemDicttypeAdd = (
  { req }: postSystemDicttypeAddProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/dicttype/add`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 新增
 * @param {any}      [req]           [required]  req
 */

export type postSystemFactorAddProps = {
  req: FactorReq;
};

export const postSystemFactorAdd = (
  { req }: postSystemFactorAddProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/factor/add`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 新增组织
 * @param {any}      [req]           [required]  req
 */

export type postSystemOrgAddProps = {
  req: OrgReq;
};

export const postSystemOrgAdd = (
  { req }: postSystemOrgAddProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/org/add`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 新增角色
 * @param {any}      [req]           [required]  req
 */

export type postSystemRoleAddProps = {
  req: RoleReq;
};

export const postSystemRoleAdd = (
  { req }: postSystemRoleAddProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/role/add`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 新增用户
 * @param {any}      [req]           [required]  req
 */

export type postSystemUserAddProps = {
  req: UserReq;
};

export const postSystemUserAdd = (
  { req }: postSystemUserAddProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/user/add`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 地址库查询
 * @param {integer}  [addressCode]   [required]  地址code
 */

export type getSystemLibAddressCodeProps = {
  addressCode: number;
};

export const getSystemLibAddressCode = (
  { addressCode }: getSystemLibAddressCodeProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultTree> => {
  let backendApiUrl = `/system/lib/address/code`;

  return axios.request<ApiResultTree>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      addressCode: addressCode,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 地址库分级查询
 * @param {integer}  [pCode]         [required]  父级地址code，省级为0
 */

export type getSystemLibAddressListProps = {
  pCode: number;
};

export const getSystemLibAddressList = (
  { pCode }: getSystemLibAddressListProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultListTree> => {
  let backendApiUrl = `/system/lib/address/list`;

  return axios.request<ApiResultListTree>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      pCode: pCode,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 地址树
 * @param {integer}  [level]            地址级别。省 1 市 2 区 3
 */

export type getSystemLibAddressTreeProps = {
  level?: number | null | undefined;
};

export const getSystemLibAddressTree = (
  { level }: getSystemLibAddressTreeProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultListTree> => {
  let backendApiUrl = `/system/lib/address/tree`;

  return axios.request<ApiResultListTree>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      level: level,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 删除组织
 * @param {any}      [req]           [required]  req
 */

export type postSystemOrgDeleteProps = {
  req: IdReq;
};

export const postSystemOrgDelete = (
  { req }: postSystemOrgDeleteProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/org/delete`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 删除角色
 * @param {any}      [req]           [required]  req
 */

export type postSystemRoleDeleteProps = {
  req: IdReq;
};

export const postSystemRoleDelete = (
  { req }: postSystemRoleDeleteProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/role/delete`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 删除用户
 * @param {any}      [req]           [required]  req
 */

export type postSystemUserDeleteProps = {
  req: IdReq;
};

export const postSystemUserDelete = (
  { req }: postSystemUserDeleteProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/user/delete`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 审批配置详情
 * @param {string}   [auditType]     [required]  审批内容
 * @param {integer}  [orgId]         [required]  组织id
 */

export type getSystemAuditOrgIdAuditTypeProps = {
  auditType: '1' | '2';
  orgId: number;
};

export const getSystemAuditOrgIdAuditType = (
  { auditType, orgId }: getSystemAuditOrgIdAuditTypeProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultAuditDetailDto> => {
  let backendApiUrl = `/system/audit/${orgId}/${auditType}`;

  return axios.request<ApiResultAuditDetailDto>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      auditType: auditType,
      orgId: orgId,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 详情
 * @param {integer}  [id]            [required]  id
 */

export type getSystemFactorIdProps = {
  id: number;
};

export const getSystemFactorId = (
  { id }: getSystemFactorIdProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultFactor> => {
  let backendApiUrl = `/system/factor/${id}`;

  return axios.request<ApiResultFactor>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      id: id,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 字段明细
 * @param {integer}  [id]            [required]  id
 */

export type getSystemI18nIdProps = {
  id: number;
};

export const getSystemI18nId = (
  { id }: getSystemI18nIdProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultI18nResp> => {
  let backendApiUrl = `/system/i18n/${id}`;

  return axios.request<ApiResultI18nResp>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      id: id,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 组织详情
 * @param {integer}  [id]            [required]  id
 */

export type getSystemOrgIdProps = {
  id: number;
};

export const getSystemOrgId = (
  { id }: getSystemOrgIdProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultOrg> => {
  let backendApiUrl = `/system/org/${id}`;

  return axios.request<ApiResultOrg>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      id: id,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 权限详情
 * @param {integer}  [id]            [required]  id
 */

export type getSystemPermissionIdProps = {
  id: number;
};

export const getSystemPermissionId = (
  { id }: getSystemPermissionIdProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultPermission> => {
  let backendApiUrl = `/system/permission/${id}`;
  backendApiUrl = backendApiUrl.replace('{id}', encodeURIComponent('' + id));

  return axios.request<ApiResultPermission>({
    url: backendApiUrl,
    method: 'GET',
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 角色详情
 * @param {integer}  [id]            [required]  id
 */

export type getSystemRoleIdProps = {
  id: number;
};

export const getSystemRoleId = (
  { id }: getSystemRoleIdProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultRole> => {
  let backendApiUrl = `/system/role/${id}`;

  return axios.request<ApiResultRole>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      id: id,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 用户详情
 * @param {integer}  [id]            [required]  id
 */

export type getSystemUserIdProps = {
  id: number;
};

export const getSystemUserId = (
  { id }: getSystemUserIdProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultUserDetailResp> => {
  let backendApiUrl = `/system/user/${id}`;

  return axios.request<ApiResultUserDetailResp>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      id: id,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 记录下载日志
 * @param {any}      [req]           [required]  req
 */

export type postSystemOperlogSaveDownloadLogProps = {
  req: DownloadLogReq;
};

export const postSystemOperlogSaveDownloadLog = (
  { req }: postSystemOperlogSaveDownloadLogProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/operlog/save/downloadLog`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 用户组织配置
 * @param {any}      [req]           [required]  req
 */

export type postSystemUserEditOrgProps = {
  req: UserOrgReq;
};

export const postSystemUserEditOrg = (
  { req }: postSystemUserEditOrgProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/user/edit/org`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 用户角色配置
 * @param {any}      [req]           [required]  req
 */

export type postSystemUserEditRoleProps = {
  req: UserRoleReq;
};

export const postSystemUserEditRole = (
  { req }: postSystemUserEditRoleProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/user/edit/role`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 编辑审批
 * @param {any}      [req]           [required]  req
 */

export type postSystemAuditEditProps = {
  req: AuditReq;
};

export const postSystemAuditEdit = (
  { req }: postSystemAuditEditProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/audit/edit`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 编辑字典分类
 * @param {any}      [req]           [required]  req
 */

export type postSystemDictdataEditProps = {
  req: DictDataReq;
};

export const postSystemDictdataEdit = (
  { req }: postSystemDictdataEditProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/dictdata/edit`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 编辑字典枚举值
 * @param {any}      [req]           [required]  req
 */

export type postSystemDictenumEditProps = {
  req: DictEnumReq;
};

export const postSystemDictenumEdit = (
  { req }: postSystemDictenumEditProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/dictenum/edit`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 编辑字典
 * @param {any}      [req]           [required]  req
 */

export type postSystemDicttypeEditProps = {
  req: DictTypeReq;
};

export const postSystemDicttypeEdit = (
  { req }: postSystemDicttypeEditProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/dicttype/edit`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 编辑
 * @param {any}      [req]           [required]  req
 */

export type postSystemFactorEditProps = {
  req: FactorReq;
};

export const postSystemFactorEdit = (
  { req }: postSystemFactorEditProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/factor/edit`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 编辑字段
 * @param {any}      [req]           [required]  req
 */

export type postSystemI18nEditProps = {
  req: SysI18nLangReq;
};

export const postSystemI18nEdit = (
  { req }: postSystemI18nEditProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/i18n/edit`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 编辑组织
 * @param {any}      [req]           [required]  req
 */

export type postSystemOrgEditProps = {
  req: OrgReq;
};

export const postSystemOrgEdit = (
  { req }: postSystemOrgEditProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/org/edit`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 编辑角色
 * @param {any}      [req]           [required]  req
 */

export type postSystemRoleEditProps = {
  req: RoleReq;
};

export const postSystemRoleEdit = (
  { req }: postSystemRoleEditProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/role/edit`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 编辑用户
 * @param {any}      [req]           [required]  req
 */

export type postSystemUserEditProps = {
  req: UserReq;
};

export const postSystemUserEdit = (
  { req }: postSystemUserEditProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/user/edit`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 查询枚举值（忽略大小写）
 * @param {string}   [enumName]      [required]  枚举名
 */

export type getSystemEnumsEnumNameProps = {
  enumName: string;
};

export const getSystemEnumsEnumName = (
  { enumName }: getSystemEnumsEnumNameProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultListEnumResp> => {
  let backendApiUrl = `/system/enums/${enumName}`;

  return axios.request<ApiResultListEnumResp>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      enumName: enumName,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 查询语言缓存
 * @param {string}   [lang]          [required]  lang
 */

export type getSystemI18nCacheLangProps = {
  lang: string;
};

export const getSystemI18nCacheLang = (
  { lang }: getSystemI18nCacheLangProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultMapstringstring> => {
  let backendApiUrl = `/system/i18n/cache/${lang}`;

  return axios.request<ApiResultMapstringstring>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      lang: lang,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 获取左侧菜单权限列表
 */

export type getSystemPermissionRouterProps = {};

export const getSystemPermissionRouter = (
  {}: getSystemPermissionRouterProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultListPermissionResp> => {
  let backendApiUrl = `/system/permission/router`;

  return axios.request<ApiResultListPermissionResp>({
    url: backendApiUrl,
    method: 'GET',
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 根据字典标识查询字典枚举值-批量查询
 * @param {string}   [dictTypes]     [required]  dictTypes
 */

export type getSystemDictenumListAllByDictTypeBatchProps = {
  dictTypes: string;
};

export const getSystemDictenumListAllByDictTypeBatch = (
  { dictTypes }: getSystemDictenumListAllByDictTypeBatchProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/dictenum/listAllByDictTypeBatch`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      dictTypes: dictTypes,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 修改默认密码
 * @param {any}      [req]           [required]  req
 */

export type postSystemUserPasswordModifyDefaultProps = {
  req: DefaultPasswordReq;
};

export const postSystemUserPasswordModifyDefault = (
  { req }: postSystemUserPasswordModifyDefaultProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/user/password/modifyDefault`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 用户修改密码
 * @param {any}      [req]           [required]  req
 */

export type postSystemUserPasswordModifyProps = {
  req: PasswordReq;
};

export const postSystemUserPasswordModify = (
  { req }: postSystemUserPasswordModifyProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/user/password/modify`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 审批配置列表-分页
 * @param {string}   [auditType]        审批内容
 * @param {integer}  [orgId]            组织id
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 */

export type getSystemAuditPageProps = {
  auditType?: '1' | '2' | null | undefined;
  orgId?: number | null | undefined;
  pageNum: number;
  pageSize: number;
};

export const getSystemAuditPage = (
  { auditType, orgId, pageNum, pageSize }: getSystemAuditPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageAuditResp> => {
  let backendApiUrl = `/system/audit/page`;

  return axios.request<ApiResultIPageAuditResp>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      auditType: auditType,
      orgId: orgId,
      pageNum: pageNum,
      pageSize: pageSize,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 字典分类列表-分页
 * @param {string}   [dictLabel]        分类名称
 * @param {string}   [dictType]      [required]  字典类型
 * @param {string}   [dictValue]        分类标识
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 */

export type getSystemDictdataPageProps = {
  dictLabel?: string | null | undefined;
  dictType: string;
  dictValue?: string | null | undefined;
  pageNum: number;
  pageSize: number;
};

export const getSystemDictdataPage = (
  {
    dictLabel,
    dictType,
    dictValue,
    pageNum,
    pageSize,
  }: getSystemDictdataPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageDictDataResp> => {
  let backendApiUrl = `/system/dictdata/page`;

  return axios.request<ApiResultIPageDictDataResp>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      dictLabel: dictLabel,
      dictType: dictType,
      dictValue: dictValue,
      pageNum: pageNum,
      pageSize: pageSize,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 角色列表-分页
 * @param {string}   [likeRoleName]     角色名称
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 */

export type getSystemRolePageProps = {
  likeRoleName?: string | null | undefined;
  pageNum: number;
  pageSize: number;
  id?: number;
};

export const getSystemRolePage = (
  { likeRoleName, pageNum, pageSize, id }: getSystemRolePageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageRole> => {
  let backendApiUrl = `/system/role/page`;

  return axios.request<ApiResultIPageRole>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      likeRoleName: likeRoleName,
      pageNum: pageNum,
      pageSize: pageSize,
      id: id,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 用户列表-分页
 * @param {string}   [likeUserInfo]     用户信息
 * @param {integer}  [orgId]            组织id
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 * @param {integer}  [roleId]           角色id
 * @param {string}   [userStatus]       用户状态。0 启用 1 禁用
 */

export type getSystemUserPageProps = {
  likeUserInfo?: string | null | undefined;
  orgId?: number | null | undefined;
  pageNum?: number;
  pageSize?: number;
  roleId?: number | null | undefined;
  userStatus?: '0' | '1' | null | undefined;
};

export const getSystemUserPage = (
  {
    likeUserInfo,
    orgId,
    pageNum,
    pageSize,
    roleId,
    userStatus,
  }: getSystemUserPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageUserResp> => {
  let backendApiUrl = `/system/user/page`;

  return axios.request<ApiResultIPageUserResp>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      likeUserInfo: likeUserInfo,
      orgId: orgId,
      pageNum: pageNum,
      pageSize: pageSize,
      roleId: roleId,
      userStatus: userStatus,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 字典枚举值列表-分页
 * @param {string}   [dictLabel]        枚举值名称
 * @param {string}   [dictType]      [required]  字典类型
 * @param {string}   [dictValue]        枚举值标识
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 * @param {string}   [sourceType]       所属分类
 */

export type getSystemDictenumPageProps = {
  dictLabel?: string | null | undefined;
  dictType: string;
  dictValue?: string | null | undefined;
  pageNum: number;
  pageSize: number;
  sourceType?: string | null | undefined;
};

export const getSystemDictenumPage = (
  {
    dictLabel,
    dictType,
    dictValue,
    pageNum,
    pageSize,
    sourceType,
  }: getSystemDictenumPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageDictEnumResp> => {
  let backendApiUrl = `/system/dictenum/page`;

  return axios.request<ApiResultIPageDictEnumResp>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      dictLabel: dictLabel,
      dictType: dictType,
      dictValue: dictValue,
      pageNum: pageNum,
      pageSize: pageSize,
      sourceType: sourceType,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 字典列表-分页
 * @param {string}   [dictName]         字典名称
 * @param {string}   [dictType]         字典类型
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 */

export type getSystemDicttypePageProps = {
  dictName?: string | null | undefined;
  dictType?: string | null | undefined;
  pageNum: number;
  pageSize: number;
};

export const getSystemDicttypePage = (
  { dictName, dictType, pageNum, pageSize }: getSystemDicttypePageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageDictTypeResp> => {
  let backendApiUrl = `/system/dicttype/page`;

  return axios.request<ApiResultIPageDictTypeResp>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      dictName: dictName,
      dictType: dictType,
      pageNum: pageNum,
      pageSize: pageSize,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 因子列表-分页
 * @param {string}   [firstClassify]    一级分类
 * @param {string}   [likeDescription]    适用场景
 * @param {string}   [likeInstitution]    发布机构
 * @param {string}   [likeName]         名称
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 * @param {string}   [secondClassify]    二级分类
 * @param {string}   [status]           状态。0 启用 1 禁用
 * @param {string}   [year]             发布年份
 * @param {string}   [likeEmissionSourceName]    排放源名称
 */

export type getSystemFactorPageProps = {
  firstClassify?: string | null | undefined;
  likeDescription?: string | null | undefined;
  likeInstitution?: string | null | undefined;
  likeName?: string | null | undefined;
  pageNum: number;
  pageSize: number;
  secondClassify?: string | null | undefined;
  status?: '0' | '1' | null | undefined;
  year?: string | null | undefined;
  ghg?: string;
  iso?: string;
  areaRepresent?: string | null | undefined;
  likeEmissionSourceName?: string | null | undefined;
};

export const getSystemFactorPage = (
  {
    firstClassify,
    likeDescription,
    likeInstitution,
    likeName,
    pageNum,
    pageSize,
    secondClassify,
    status,
    year,
    ghg,
    iso,
    areaRepresent,
    likeEmissionSourceName,
  }: getSystemFactorPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageFactor> => {
  let backendApiUrl = `/system/factor/page`;

  return axios.request<ApiResultIPageFactor>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      firstClassify: firstClassify,
      likeDescription: likeDescription,
      likeInstitution: likeInstitution,
      likeName: likeName,
      pageNum: pageNum,
      pageSize: pageSize,
      secondClassify: secondClassify,
      status: status,
      year: year,
      ghg: ghg,
      iso: iso,
      areaRepresent: areaRepresent,
      likeEmissionSourceName: likeEmissionSourceName,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 文件下载列表
 * @param {string}   [bizModule]        功能模块。1 系统管理；2 排放因子库；3 产品碳足迹；4 企业碳核算
 * @param {integer}  [orgId]            组织id
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 */

export type getSystemFilelogPageProps = {
  bizModule?: '1' | '2' | '3' | '4' | null | undefined;
  orgId?: number | null | undefined;
  pageNum: number;
  pageSize: number;
  likeFileName?: string | null | undefined;
  likeCreateByName?: string | null | undefined;
};

export const getSystemFilelogPage = (
  {
    bizModule,
    orgId,
    pageNum,
    pageSize,
    likeCreateByName,
    likeFileName,
  }: getSystemFilelogPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageFileLog> => {
  let backendApiUrl = `/system/filelog/page`;

  return axios.request<ApiResultIPageFileLog>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      bizModule: bizModule,
      orgId: orgId,
      pageNum: pageNum,
      pageSize: pageSize,
      likeCreateByName,
      likeFileName,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 字段列表-分页
 * @param {string}   [i18nType]         所属产品。1 通用 2 错误码 3 系统管理 4 碳因子库 5 组织碳核算 6 产品碳阻迹 7 供应链 8 碳账户 9 降碳课题
 * @param {string}   [likeFieldKey]     字段标识
 * @param {string}   [likeFieldName]    字段名称
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 */

export type getSystemI18nPageProps = {
  i18nType?: '1' | '2' | '3' | null | undefined;
  likeFieldKey?: string | null | undefined;
  likeFieldName?: string | null | undefined;
  pageNum: number;
  pageSize: number;
};

export const getSystemI18nPage = (
  {
    i18nType,
    likeFieldKey,
    likeFieldName,
    pageNum,
    pageSize,
  }: getSystemI18nPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageI18n> => {
  let backendApiUrl = `/system/i18n/page`;

  return axios.request<ApiResultIPageI18n>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      i18nType: i18nType,
      likeFieldKey: likeFieldKey,
      likeFieldName: likeFieldName,
      pageNum: pageNum,
      pageSize: pageSize,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 操作日志列表
 * @param {string}   [endDate]          结束时间
 * @param {string}   [likeUsername]     操作人姓名或账号
 * @param {string}   [moduleType]       模块类型
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 * @param {string}   [startDate]        开始时间
 */

export type getSystemOperlogPageProps = {
  endDate?: string | null | undefined;
  likeUsername?: string | null | undefined;
  moduleType?:
    | '10'
    | '11'
    | '12'
    | '13'
    | '14'
    | '15'
    | '16'
    | '17'
    | '20'
    | '30'
    | '31'
    | '32'
    | '33'
    | '34'
    | '35'
    | '36'
    | '37'
    | null
    | undefined;
  pageNum: number;
  pageSize: number;
  startDate?: string | null | undefined;
};

export const getSystemOperlogPage = (
  {
    endDate,
    likeUsername,
    moduleType,
    pageNum,
    pageSize,
    startDate,
  }: getSystemOperlogPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageOperLog> => {
  let backendApiUrl = `/system/operlog/page`;

  return axios.request<ApiResultIPageOperLog>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      endDate: endDate,
      likeUsername: likeUsername,
      moduleType: moduleType,
      pageNum: pageNum,
      pageSize: pageSize,
      startDate: startDate,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 组织列表-分页
 * @param {string}   [likeOrgName]      组织名称
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 */

export type getSystemOrgPageProps = {
  likeOrgName?: string | null | undefined;
  pageNum: number;
  pageSize: number;
};

export const getSystemOrgPage = (
  { likeOrgName, pageNum, pageSize }: getSystemOrgPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageOrg> => {
  let backendApiUrl = `/system/org/page`;

  return axios.request<ApiResultIPageOrg>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      likeOrgName: likeOrgName,
      pageNum: pageNum,
      pageSize: pageSize,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 权限列表-分页
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 */

export type getSystemPermissionPageProps = {
  pageNum: number;
  pageSize: number;
};

export const getSystemPermissionPage = (
  { pageNum, pageSize }: getSystemPermissionPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPagePermission> => {
  let backendApiUrl = `/system/permission/page`;

  return axios.request<ApiResultIPagePermission>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      pageNum: pageNum,
      pageSize: pageSize,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 重新缓存
 */

export type getSystemI18nReCacheProps = {};

export const getSystemI18nReCache = (
  {}: getSystemI18nReCacheProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/i18n/reCache`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'GET',
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 重新缓存权限点名称
 */

export type getSystemPermissionReCacheProps = {};

export const getSystemPermissionReCache = (
  {}: getSystemPermissionReCacheProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/permission/reCache`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'GET',
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 管理员重置密码
 * @param {any}      [req]           [required]  req
 */

export type postSystemUserPasswordResetProps = {
  req: IdReq;
};

export const postSystemUserPasswordReset = (
  { req }: postSystemUserPasswordResetProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/user/password/reset`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 启用禁用
 * @param {any}      [req]           [required]  req
 */

export type postSystemFactorStatusProps = {
  req: EnableStatusReq;
};

export const postSystemFactorStatus = (
  { req }: postSystemFactorStatusProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/factor/status`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 启用禁用用户
 * @param {any}      [req]           [required]  req
 */

export type postSystemUserStatusProps = {
  req: UserStatusReq;
};

export const postSystemUserStatus = (
  { req }: postSystemUserStatusProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/user/status`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 切换语言
 * @param {string}   [lang]          [required]  lang
 */

export type getSystemI18nSwitchLangProps = {
  lang: string;
};

export const getSystemI18nSwitchLang = (
  { lang }: getSystemI18nSwitchLangProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultMapstringstring> => {
  let backendApiUrl = `/system/i18n/switch/${lang}`;

  return axios.request<ApiResultMapstringstring>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      lang: lang,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 组织树
 * @param {integer}  [userId]           用户id
 */

export type getSystemOrgTreeProps = {
  userId?: number | null | undefined;
};

export const getSystemOrgTree = (
  { userId }: getSystemOrgTreeProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultorg树> => {
  let backendApiUrl = `/system/org/tree`;

  return axios.request<ApiResultorg树>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      userId: userId,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 权限树
 * @param {integer}  [roleId]           角色id
 */

export type getSystemPermissionTreeProps = {
  roleId?: number | null | undefined;
};

export const getSystemPermissionTree = (
  { roleId }: getSystemPermissionTreeProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult树> => {
  let backendApiUrl = `/system/permission/tree`;

  return axios.request<ApiResult树>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      roleId: roleId,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 新增单位换算
 * @param {any}      [req]           [required]  req
 */

export type postSystemLibUnitAddProps = {
  req: LibUnitConversionReq;
};

export const postSystemLibUnitAdd = (
  { req }: postSystemLibUnitAddProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/lib/unit/add`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 单位换算比例
 * @param {integer}  [unitFrom]      [required]  unitFrom
 * @param {integer}  [unitTo]        [required]  unitTo
 */

export type getSystemLibUnitUnitConvertProps = {
  unitFrom: number;
  unitTo: number;
};

export const getSystemLibUnitUnitConvert = (
  { unitFrom, unitTo }: getSystemLibUnitUnitConvertProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultstring> => {
  let backendApiUrl = `/system/lib/unit/unitConvert`;

  return axios.request<ApiResultstring>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      unitFrom: unitFrom,
      unitTo: unitTo,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 删除单位换算
 * @param {any}      [req]           [required]  req
 */

export type postSystemLibUnitDeleteProps = {
  req: IdReq;
};

export const postSystemLibUnitDelete = (
  { req }: postSystemLibUnitDeleteProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/lib/unit/delete`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 编辑单位换算
 * @param {any}      [req]           [required]  req
 */

export type postSystemLibUnitEditProps = {
  req: LibUnitConversionReq;
};

export const postSystemLibUnitEdit = (
  { req }: postSystemLibUnitEditProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/lib/unit/edit`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'POST',
    data: req,
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 单位换算列表-分页
 * @param {integer}  [pageNum]       [required]  页码
 * @param {integer}  [pageSize]      [required]  每页条数
 * @param {integer}  [unit]             单位
 * @param {integer}  [unitClass]        单位类别
 */

export type getSystemLibUnitPageProps = {
  pageNum: number;
  pageSize: number;
  unit?: number | null | undefined;
  unitClass?: number | null | undefined;
};

export const getSystemLibUnitPage = (
  { pageNum, pageSize, unit, unitClass }: getSystemLibUnitPageProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultIPageLibUnitConversion> => {
  let backendApiUrl = `/system/lib/unit/page`;

  return axios.request<ApiResultIPageLibUnitConversion>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      pageNum: pageNum,
      pageSize: pageSize,
      unit: unit,
      unitClass: unitClass,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description 用户所属组织下拉框
 * @param {string}   [likeOrgName]      组织名称
 */

export type getSystemOrgUserListProps = {
  likeOrgName?: string | null | undefined;
};

export const getSystemOrgUserList = (
  { likeOrgName }: getSystemOrgUserListProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultListOrgPojo> => {
  let backendApiUrl = `/system/org/user/list`;

  return axios.request<ApiResultListOrgPojo>({
    url: backendApiUrl,
    method: 'GET',
    params: serializeQueryParam({
      likeOrgName: likeOrgName,
    }),
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description cache
 * @param {string}   [key]           [required]  key
 */

export type getSystemCacheKeyProps = {
  key: string;
};

export const getSystemCacheKey = (
  { key }: getSystemCacheKeyProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResultListDictEnum> => {
  let backendApiUrl = `/system/cache/${key}`;
  backendApiUrl = backendApiUrl.replace('{key}', encodeURIComponent('' + key));

  return axios.request<ApiResultListDictEnum>({
    url: backendApiUrl,
    method: 'GET',
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description coreUrl
 */

export type getSystemCoreProps = {};

export const getSystemCore = (
  {}: getSystemCoreProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<unknown> => {
  let backendApiUrl = `/system/core`;

  return axios.request<unknown>({
    url: backendApiUrl,
    method: 'GET',
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description flush
 */

export type getSystemFlushProps = {};

export const getSystemFlush = (
  {}: getSystemFlushProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<ApiResult> => {
  let backendApiUrl = `/system/flush`;

  return axios.request<ApiResult>({
    url: backendApiUrl,
    method: 'GET',
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

/**
 * @description health
 */

export type getSystemHealthProps = {};

export const getSystemHealth = (
  {}: getSystemHealthProps,
  $config?: AxiosRequestConfig,
): AxiosPromise<string> => {
  let backendApiUrl = `/system/health`;

  return axios.request<string>({
    url: backendApiUrl,
    method: 'GET',
    // baseURL: `${process.env.REACT_APP_API_URL}`,
    ...$config,
  });
};

function serializeQueryParam(obj?: Record<string, any>) {
  if (obj === null || typeof obj !== 'object') return '';
  // if (obj instanceof Date) return obj.toJSON();
  // if (typeof obj !== 'object' || Array.isArray(obj)) return obj;
  let newObj: Record<string, any> = {};
  Object.entries(obj).forEach(([k, val]) => {
    if (![NaN, null, undefined].includes(val)) newObj[k] = val;
  });
  return newObj;
}
export interface ApiResult {
  code?: number;
  data?: unknown;
  msg?: string;
}

export interface ApiResultAuditDetailDto {
  code?: number;
  data?: AuditDetailDto;
  msg?: string;
}

export interface ApiResultFactor {
  code?: number;
  data?: Factor;
  msg?: string;
}

export interface ApiResultI18nResp {
  code?: number;
  data?: I18nResp;
  msg?: string;
}

export interface ApiResultIPageAuditResp {
  code?: number;
  data?: IPageAuditResp;
  msg?: string;
}

export interface ApiResultIPageDictDataResp {
  code?: number;
  data?: IPageDictDataResp;
  msg?: string;
}

export interface ApiResultIPageDictEnumResp {
  code?: number;
  data?: IPageDictEnumResp;
  msg?: string;
}

export interface ApiResultIPageDictTypeResp {
  code?: number;
  data?: IPageDictTypeResp;
  msg?: string;
}

export interface ApiResultIPageFactor {
  code?: number;
  data?: IPageFactor;
  msg?: string;
}

export interface ApiResultIPageFileLog {
  code?: number;
  data?: IPageFileLog;
  msg?: string;
}

export interface ApiResultIPageI18n {
  code?: number;
  data?: IPageI18n;
  msg?: string;
}

export interface ApiResultIPageLibUnitConversion {
  code?: number;
  data?: IPageLibUnitConversion;
  msg?: string;
}

export interface ApiResultIPageOperLog {
  code?: number;
  data?: IPageOperLog;
  msg?: string;
}

export interface ApiResultIPageOrg {
  code?: number;
  data?: IPageOrg;
  msg?: string;
}

export interface ApiResultIPagePermission {
  code?: number;
  data?: IPagePermission;
  msg?: string;
}

export interface ApiResultIPageRole {
  code?: number;
  data?: IPageRole;
  msg?: string;
}

export interface ApiResultIPageUserResp {
  code?: number;
  data?: IPageUserResp;
  msg?: string;
}

export interface ApiResultListDictEnum {
  code?: number;
  data?: DictEnum[];
  msg?: string;
}

export interface ApiResultListEnumResp {
  code?: number;
  data?: EnumResp[];
  msg?: string;
}

export interface ApiResultListOrgPojo {
  code?: number;
  data?: OrgPojo[];
  msg?: string;
}

export interface ApiResultListPermissionResp {
  code?: number;
  data?: PermissionResp[];
  msg?: string;
}

export interface ApiResultListTree {
  code?: number;
  data?: Tree[];
  msg?: string;
}

export interface ApiResultMapstringstring {
  code?: number;
  data?: { [key: string]: string };
  msg?: string;
}

export interface ApiResultOrg {
  code?: number;
  data?: Org;
  msg?: string;
}

export interface ApiResultPermission {
  code?: number;
  data?: Permission;
  msg?: string;
}

export interface ApiResultRole {
  code?: number;
  data?: Role;
  msg?: string;
}

export interface ApiResultTree {
  code?: number;
  data?: Tree;
  msg?: string;
}

export interface ApiResultUserDetailResp {
  code?: number;
  data?: UserDetailResp;
  msg?: string;
}

export interface ApiResultorg树 {
  code?: number;
  data?: org树;
  msg?: string;
}

export interface ApiResultstring {
  code?: number;
  data?: string;
  msg?: string;
}

export interface ApiResult树 {
  code?: number;
  data?: 树;
  msg?: string;
}

export interface AuditDetailDto {
  auditType?: '1' | '2';

  companyId?: number;

  nodeList?: AuditNodeDto[];

  orgId?: number;
}

export interface AuditNodeDto {
  auditOrgId?: number;

  configType?: '1' | '2';

  id?: number;

  nodeLevel?: number;

  nodeName?: string;

  targetIds?: number[];
}

export interface AuditReq {
  auditType?: '1' | '2';

  nodeList?: AuditNodeDto[];

  orgId?: number;
}

export interface AuditResp {
  auditType?: '1' | '2';

  companyId?: number;

  createBy?: number;

  createTime?: Date;
  id?: number;

  orgId?: number;

  orgName?: string;

  updateBy?: number;

  updateByName?: string;

  updateTime?: Date;
}

export interface DefaultPasswordReq {
  newPassword?: string;
}

export interface DictDataReq {
  createBy?: number;
  createTime?: Date;

  dictLabel?: string;

  dictSort?: number;

  dictType?: string;

  dictValue?: string;

  id?: number;
  updateBy?: number;
  updateTime?: Date;
}

export interface DictDataResp {
  dictLabel?: string;

  dictSort?: number;

  dictType?: string;

  dictValue?: string;

  id?: number;
}

export interface DictEnum {
  createBy?: number;
  createTime?: Date;

  dictLabel?: string;

  dictSort?: number;

  dictType?: string;

  dictValue?: string;

  id?: number;

  relatedValue?: string;

  remark?: string;

  sourceType?: string;

  status?: string;
  updateBy?: number;
  updateTime?: Date;
}

export interface DictEnumReq {
  createBy?: number;
  createTime?: Date;

  dictLabel?: string;

  dictSort?: number;

  dictType?: string;

  dictValue?: string;

  id?: number;

  relatedValue?: string;

  sourceType?: string;
  updateBy?: number;
  updateTime?: Date;
}

export interface DictEnumResp {
  dictLabel?: string;

  dictSort?: number;

  dictType?: string;

  dictValue?: string;

  id?: number;

  relatedValue?: string;

  sourceType?: string;

  sourceTypeName?: string;
}

export interface DictTypeReq {
  createBy?: number;
  createTime?: Date;

  dictName?: string;

  dictType?: string;

  id?: number;
  updateBy?: number;
  updateTime?: Date;
  [key: string]: any;
}

export interface DictTypeResp {
  dictName?: string;

  dictType?: string;

  id?: number;
}

export interface DownloadLogReq {
  content: string;

  moduleType:
    | '10'
    | '11'
    | '12'
    | '13'
    | '14'
    | '15'
    | '16'
    | '17'
    | '20'
    | '30'
    | '31'
    | '32'
    | '33'
    | '34'
    | '35'
    | '36'
    | '37';

  url?: string;
}

export interface EnableStatusReq {
  id?: number;

  status?: '0' | '1';
}

export interface EnumResp {
  code?: number;
  name?: string;
  score?: string;
  subList?: EnumResp[];
}

export interface Factor {
  createBy?: number;

  createTime?: Date;

  deleted?: boolean;

  description?: string;

  factorValue?: string;

  firstClassify?: string;

  gasList?: FactorGasRes[];

  id?: number;

  institution?: string;

  name?: string;

  secondClassify?: string;

  source?: string;

  sourceLanguage?: string;

  sourceLanguageName?: string;

  sourceLevel?: string;

  status?: '0' | '1';

  unit?: string;

  updateBy?: number;

  updateByName?: string;

  updateTime?: Date;

  url?: string;

  year?: string;
  areaRepresent?: string;
  languageSourceList?: any[];
  /** 拼接的排放源名称（组织编码） */
  emissionSourceName?: string;
}

export interface FactorGasReq {
  createBy?: number;

  createTime?: Date;

  factorId?: number;

  factorUnitM?: string;

  factorUnitZ?: string;

  factorValue?: string;

  gas?: string;

  gasType?: string;

  id?: number;

  updateBy?: number;

  updateTime?: Date;
}

export interface FactorGasRes {
  createBy?: number;

  createTime?: Date;

  factorId?: number;

  factorUnitM?: string;

  factorUnitZ?: string;

  factorValue?: string;

  gas?: string;

  gasType?: string;

  id?: number;

  updateBy?: number;

  updateTime?: Date;
  valid?: boolean;
}

export interface FactorReq {
  createBy?: number;
  createTime?: Date;

  description?: string;

  firstClassify?: string;

  gasList?: FactorGasReq[];

  id?: number;

  institution?: string;

  name?: string;

  secondClassify?: string;

  source?: string;

  sourceLanguage?: string;

  sourceLanguageName?: string;

  sourceLevel?: string;
  updateBy?: number;
  updateTime?: Date;

  url?: string;

  year?: string;
  languageSourceList?: {
    langType: number;
    sourceType: any;
    sourceValue: any;
    id: any;
  }[];
}

export interface FileLog {
  bizModule?: '1' | '2' | '3' | '4';

  companyId?: number;

  createBy?: number;

  createByName?: string;

  createTime?: Date;

  deleted?: boolean;

  fileName?: string;

  filePath?: string;

  fileStatus?: '-1' | '0' | '1';

  fileUrl?: string;

  id?: number;

  orgId?: number;

  updateBy?: number;

  updateByName?: string;

  updateTime?: Date;
}

export interface I18n {
  createBy?: number;

  createTime?: Date;

  deleted?: boolean;

  fieldKey?: string;

  fieldName?: string;

  fieldNameEn?: string;

  i18nType?: '1' | '2' | '3';

  id?: number;

  updateBy?: number;

  updateByUsername?: string;

  updateTime?: Date;
}

export interface I18nResp {
  fieldKey?: string;

  fieldName?: string;

  i18nType?: '1' | '2' | '3';

  id?: number;

  langList?: SysI18nLang[];
}

export interface IPageAuditResp {
  list?: AuditResp[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageDictDataResp {
  list?: DictDataResp[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageDictEnumResp {
  list?: DictEnumResp[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageDictTypeResp {
  list?: DictTypeResp[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageFactor {
  list?: Factor[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageFileLog {
  list?: FileLog[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageI18n {
  list?: I18n[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageLibUnitConversion {
  list?: LibUnitConversion[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageOperLog {
  list?: OperLog[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageOrg {
  list?: Org[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPagePermission {
  list?: Permission[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageRole {
  list?: Role[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IPageUserResp {
  list?: UserResp[];

  pageNum?: number;

  pageSize?: number;

  pages?: number;

  size?: number;

  total?: number;
}

export interface IdReq {
  id: number;
}

export interface LibUnitConversion {
  createBy?: number;

  createTime?: Date;

  deleted?: boolean;

  id?: number;

  unitClass?: number;

  unitFrom?: number;

  unitTo?: number;

  unitValue?: string;

  updateBy?: number;

  updateByName?: string;

  updateTime?: Date;
}

export interface LibUnitConversionReq {
  id?: number;

  unitClass?: number;

  unitFrom?: number;

  unitTo?: number;

  unitValue?: string;
}

export interface OperLog {
  companyId?: number;

  content?: string;

  createBy?: number;

  createTime?: Date;

  id?: number;

  moduleType?:
    | '10'
    | '11'
    | '12'
    | '13'
    | '14'
    | '15'
    | '16'
    | '17'
    | '20'
    | '30'
    | '31'
    | '32'
    | '33'
    | '34'
    | '35'
    | '36'
    | '37';

  operType?: '1' | '2' | '3';

  realName?: string;
  updateBy?: number;
  updateTime?: Date;

  username?: string;
}

export interface Org {
  companyId?: number;

  createBy?: number;

  createTime?: Date;

  deleted?: boolean;

  id?: number;

  orgAbbr?: string;

  orgCode?: string;

  orgInfo?: string;

  orgName?: string;

  orgPath?: string;

  orgType?: '0' | '1' | '2' | '3';

  pid?: number;

  updateBy?: number;

  updateByName?: string;

  updateTime?: Date;
  languageSourceList?: any[];
}

export interface OrgPojo {
  id?: number;

  orgCode?: string;

  orgName?: string;

  orgType?: '0' | '1' | '2' | '3';

  pid?: number;

  orgStatus?: number;
}

export interface OrgReq {
  id?: number;

  orgAbbr?: string;

  orgCode?: string;

  orgInfo?: string;

  orgName?: string;

  orgType?: '0' | '1' | '2' | '3';

  pid?: number;
  languageSourceList?: any[];
}

export interface OrgTree {
  disabled?: boolean;
  orgStatus?: number;
  abbr?: string;
  children?: OrgTree[];

  code?: number;

  name?: string;

  orgCode?: string;

  orgType?: '0' | '1' | '2' | '3';

  pcode?: number;
  region?: string;

  updateBy?: number;

  updateByName?: string;

  updateTime?: Date;
  level?: number;
}

export interface PasswordReq {
  newPassword?: string;

  oldPassword?: string;
}

export interface Permission {
  createBy?: number;

  createTime?: Date;

  deleted?: boolean;

  icon?: string;

  id?: number;

  menuType?: 'C' | 'F' | 'M';

  orderNum?: number;

  path?: string;

  permissionName?: string;

  perms?: string;

  pid?: number;

  remark?: string;

  updateBy?: number;

  updateTime?: Date;
}

export interface PermissionResp {
  icon?: string;

  id?: number;

  menuType?: 'C' | 'F' | 'M';

  orderNum?: number;

  path?: string;

  permissionName?: string;

  perms?: string;

  pid?: number;

  remark?: string;
}

export interface Role {
  companyId?: number;

  createBy?: number;

  createTime?: Date;

  deleted?: boolean;

  id?: number;

  roleInfo?: string;

  roleName?: string;

  roleType?: '0' | '1';

  updateBy?: number;

  updateByName?: string;

  updateTime?: Date;

  linkUser?: boolean;
}

export interface RoleReq {
  allCheckedList?: number[];

  halfCheckedList?: number[];

  id?: number;

  roleInfo?: string;

  roleName?: string;
}

export interface SysI18nLang {
  fieldKey?: string;

  langDict?: string;

  langValue?: string;
}

export interface SysI18nLangReq {
  fieldKey?: string;

  langList?: SysI18nLang[];
}

export interface Tree {
  children?: Tree[];
  code?: number;
  name?: string;
  pcode?: number;
}

export interface UserDetailResp {
  id?: number;

  lastLoginTime?: Date;

  mobile?: string;

  orgList?: Org[];

  orgNames?: string;

  realName?: string;

  roleList?: Role[];

  roleNames?: string;

  userStatus?: '0' | '1';

  username?: string;
}

export interface UserOrgReq {
  allCheckedList?: number[];

  halfCheckedList?: number[];

  id?: number;
}

export interface UserReq {
  createBy?: number;

  createTime?: Date;

  defaultPassword?: boolean;

  id?: number;

  lastLoginTime?: Date;

  mobile?: string;

  orgs?: string;

  realName?: string;

  roles?: string;

  updateBy?: number;

  updateTime?: Date;

  /** 0 - 启用 1 - 禁用 */
  userStatus?: number;

  username?: string;
}

export interface UserResp {
  userStatus_name?: string;

  adminFlag?: boolean;

  companyId?: number;

  defaultPassword?: boolean;

  deleted?: boolean;

  id?: number;

  lastLoginTime?: Date;

  mobile?: string;

  orgNames?: string;

  realName?: string;

  roleNames?: string;

  updateBy?: number;

  updateByName?: string;

  updateTime?: Date;

  /** 0 - 启用 1 - 禁用 */
  userStatus?: number;

  username?: string;
}

export interface UserRoleReq {
  id?: number;

  idList?: number[];
}

export interface UserStatusReq {
  id?: number;

  /** 0 - 启用 1 - 禁用 */
  userStatus?: number;
}

export interface org树 {
  allCheckedList?: number[];

  halfCheckedList?: number[];

  tree?: OrgTree[];
}

export interface 树 {
  allCheckedList?: number[];

  halfCheckedList?: number[];

  tree?: Tree[];
}
