/** 供应链碳管理迁移路由（与系统管理/设置同级） */
export enum SupplyChainRefRouteMaps {
  supplyChainCarbon = '/sys/supplyChainCarbon',
  tasks = '/sys/supplyChainCarbon/tasks',
  supplierDataFill = '/sys/supplyChainCarbon/supplierDataFill',
  supplierDataFillInfo = '/sys/supplyChainCarbon/supplierDataFill/:id',
  questionnaire = '/sys/supplyChainCarbon/questionnaire',
  questionnaireCreate = '/sys/supplyChainCarbon/questionnaire/create',
  questionnaireInfo = '/sys/supplyChainCarbon/questionnaire/:id',
  questionnaireEdit = '/sys/supplyChainCarbon/questionnaire/:id/edit',
  questionnaireResponses = '/sys/supplyChainCarbon/questionnaire/:id/responses',
  assessmentReports = '/sys/supplyChainCarbon/assessmentReports',
  assessmentReportInfo = '/sys/supplyChainCarbon/assessmentReports/:id',
  targetMgmt = '/sys/supplyChainCarbon/targetMgmt',
  targetInfo = '/sys/supplyChainCarbon/targetMgmt/:pageTypeInfo/:id',
  plans = '/sys/supplyChainCarbon/plans',
  planInfo = '/sys/supplyChainCarbon/plans/:id',
  progress = '/sys/supplyChainCarbon/progress',
  certificates = '/sys/supplyChainCarbon/certificates',
  basicConfig = '/sys/basicConfig',
  training = '/sys/basicConfig/training',
  trainingInfo = '/sys/basicConfig/training/:pageTypeInfo/:id',
  formTemplates = '/sys/basicConfig/formTemplates',
  formTemplateCreate = '/sys/basicConfig/formTemplates/create',
  formTemplateInfo = '/sys/basicConfig/formTemplates/:id',
}
